export const GENERATION_STAGES = {
  REQUIREMENTS_EXTRACTION: 'requirements_extraction',
  COMPANY_BRIEF: 'company_brief',
  ROLE_ANALYSIS: 'role_analysis',
  ANALYSIS_COMPLETED: 'analysis_completed',
  QUESTION_GENERATION: 'question_generation',
  FLASHCARD_GENERATION: 'flashcard_generation',
  COVERAGE_CHECK: 'coverage_check',
  COVERAGE_SECOND_PASS: 'coverage_second_pass',
  SCHEDULE_GENERATION: 'schedule_generation',
  GENERATION_COMPLETED: 'generation_completed'
};

export const STAGE_PROGRESS = {
  [GENERATION_STAGES.REQUIREMENTS_EXTRACTION]: 20,
  [GENERATION_STAGES.COMPANY_BRIEF]: 45,
  [GENERATION_STAGES.ROLE_ANALYSIS]: 70,
  [GENERATION_STAGES.ANALYSIS_COMPLETED]: 75,
  [GENERATION_STAGES.QUESTION_GENERATION]: 80,
  [GENERATION_STAGES.FLASHCARD_GENERATION]: 86,
  [GENERATION_STAGES.COVERAGE_CHECK]: 90,
  [GENERATION_STAGES.COVERAGE_SECOND_PASS]: 94,
  [GENERATION_STAGES.SCHEDULE_GENERATION]: 97,
  [GENERATION_STAGES.GENERATION_COMPLETED]: 100
};

export const GENERATION_DEFAULTS = {
  maxRetries: 3,
  timeoutMs: 15000,
  maxPageCharsForLlm: 3000,
  maxTotalResearchChars: 12000
};
